### ISSUE TITLE
ProtoBuf相关的类没提交吧？编译报错咯

### ISSUE THREAD

**Issue by qwpking** [yicaoyimuys/EgretGameEngine#4]

**Comment by yicaoyimuys** [comment]
尴尬，漏传了，已更新

**Comment by reason211** [comment]
版本 4.1.0.
最新版编译还是有问题呀，麻烦大佬看下，谢谢啦
EgretGameEngine/librarys/protobuf/bin/ProtoBuf.d.ts (5,11): Duplicate identifier 'ProtoBuf'.
EgretGameEngine/libs/modules/eui/eui.d.ts (187,46): Cannot find name 'Promise'.

**Comment by reason211** [comment]
试了下一个早上，分享下我的一个解决方法：
1. 将 librarys 这个目录剪切到项目外面一层
2. egretProperties.json 文件添加一行的 modules 里添加一行：`{
            "name": "protobuf",
            "path": "../librarys/protobuf"
        }`
3. tsconfig.json 修改下compilerOptions：
 `"compilerOptions": {
        "target": "es5",
        "lib": ["es5", "dom", "es2015.promise"]
    },`
4. 然后项目清理下，重新编译。

**Comment by yicaoyimuys** [comment]
之前是tsconfig.json漏传了 尴尬
