### ISSUE TITLE
多个Module共享一份数据

### ISSUE THREAD

**Issue by Yettyzyt** [yicaoyimuys/EgretGameEngine#6]
多个Module共享一份数据，比如用户信息（金币、体力等），需要怎么处理，每次都需要去更新用户模块的model么？

**Comment by yicaoyimuys** [comment]
如果金币、体力等数据更新涉及到UI的变化，建议在不同模块间进行消息订阅，使用Message通知各模块进行更新，如果只是进行数据读取，可使用App.ControllerManager.getControllerModel
